version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    branches:
        only:
            - master
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "easycrypt/build.gradle" }}
      - run:
          name: Download Keystore
          command: bash ./download_keystore.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "easycrypt/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: easycrypt/build/reports
          destination: reports
      - store_test_results:
          path: easycrypt/build/test-results
      - run:
          name: Gradle install and upload to bintray
          command: ./gradlew install bintrayUpload
